### PR TITLE
Symfony2.0 compatibility

### PR DESCRIPTION
**Pull request by henrikbjorn**
Changed a few things, mainly the tests to include CDATA. There is only one failure which i cant seem to get why is failing.

```
[Symfony2.0Compatibility][~/Code/SimpleThingsFormSerializerBundle] phpunit
PHPUnit 3.6.11 by Sebastian Bergmann.

Configuration read from /Users/Henrik/Code/SimpleThingsFormSerializerBundle/phpunit.xml.dist

...F.....

Time: 0 seconds, Memory: 10.50Mb

There was 1 failure:

1) SimpleThings\FormSerializerBundle\Tests\Serializer\FormSerializerTest::testFunctional
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
   <country><![CDATA[DE]]></country>
-  <address zip_code="12345" city="Bonn"><![CDATA[Somestreet 1]]></address>
+  <address zip_code="" city=""><![CDATA[]]></address>
 </user>
 '

/Users/Henrik/Code/SimpleThingsFormSerializerBundle/Tests/Serializer/FormSerializerTest.php:98
/usr/local/php5-20120720-140003/bin/phpunit:46

FAILURES!
Tests: 9, Assertions: 11, Failures: 1.
```

The weird part is that it work if testFunctional just uses the AddressType, so it must be something about adding via the FormBuilder.

### CODE REVIEW

**Comment by beberlei** [comment]
@henrikbjorn composer.json is also missing still.

**Comment by henrikbjorn** [comment]
Missing?

**Comment by beberlei** [comment]
not missing, but its still pointing to 2.1.\* versions.

**Comment by henrikbjorn** [comment]
https://github.com/simplethings/SimpleThingsFormSerializerBundle/blob/Symfony2.0Compatibility/composer.json this points to 2.0.\* right? also there is no minimum stability

**Comment by beberlei** [comment]
weird, i thought its still missing.

**Pull request merged**
