### PR TITLE
simple_things_form_serializer.form.extension.serializer_type

### PR DESCRIPTION
**Pull request by lsmith77**

### CODE REVIEW

**Comment by beberlei** [comment]
Why?

**Comment by stof** [comment]
type extensions are retrieved from the container at runtime: https://github.com/symfony/Form/blob/master/Extension/DependencyInjection/DependencyInjectionExtension.php#L65

**Comment by lsmith77** [comment]
exactly

**Comment by lsmith77** [comment]
not sure if other services also need to be made public

**Comment by stof** [comment]
The second type extension does

**Pull request merged**
